language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl-bin
    # - LISP=ccl-bin
    # - LISP=abcl
    # - LISP=clisp
    # - LISP=ecl
    # - LISP=cmucl
    # - LISP=alisp

install:
  # Install roswell
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh

script:
  - roswell -e '(ql:quickload :breeze)'
            -e '(breeze.selftest:selftest)'
