FROM breeze-demo-recorder-base:latest

RUN mkdir -p /breeze /tmp
WORKDIR /breeze

RUN echo | quicklisp init && quicklisp install
RUN echo '(load "/quicklisp/setup.lisp")' > /.sbclrc
COPY . .
RUN sbcl --load /quicklisp/setup.lisp \
     --script scripts/demo/setup-demo.lisp

CMD [ "scripts/demo/demo-recorder.sh", "run" ]