spec:
  inputs:
    test-name:
    script:
    breeze-listener:
      default: ""
---
emacs-$[[ inputs.test-name ]]:
  image: $CI_REGISTRY_IMAGE/breeze-ci-emacs:latest
  variables:
    BREEZE_LISTENER: $[[ inputs.breeze-listener ]]
  script:
    - $[[ inputs.script ]]
