:PROPERTIES:
:ID:       306350c9-0fb5-478b-958b-b35cae726280
:END:
#+title: Getting Started

* Clone

Clone this repository, for example, in quicklisp's local-projects
folder.

#+begin_src shell
git clone --recursive git@codeberg.org:fstamour/breeze.git ~/quicklisp/local-projects/breeze
#+end_src

* Get the dependencies

Obviously, you should have a lisp implementation installed. In doubt,
just use [[https://www.sbcl.org/][sbcl]], it is very eazy to switch implementations anytime.

For getting the libraries that breeze depends on, we suggest using
[[https://www.quicklisp.org/beta/][quicklisp]], but in any case breeze only has 3 dependencies, of which
only 2 needs to be installed (the other one, =uiop=, is part of =asdf=
and is probably included with your lisp implementation):
- [[https://gitlab.common-lisp.net/asdf/asdf/-/tree/master/uiop?ref_type=heads][=uiop=]], the Utilities for Implementation- and OS- Portability
  - it is part of [[https://asdf.common-lisp.dev/][=asdf=]], so you should already have it.
- [[https://gitlab.common-lisp.net/alexandria/alexandria][=alexandria=]] a conservative set of portable public domain utilities
- [[https://github.com/sionescu/bordeaux-threads][=bordeaux-threads=]], portable threading library
- (optional) [[https://www.xach.com/lisp/quickproject/][quickproject]]

* Load it

This will make sure that you have all the dependencies installed. And
will make it load faster for next time. For example, if breeze is
initialized by the editor, it would be much faster to load breeze if
there are fast loading files (*.fasl) ready to be loaded.

In the lisp repl of you choice:

#+begin_src lisp
;; Using quicklisp to install the dependencies as well as loading breeze
(ql:quickload "breeze")
#+end_src

#+begin_src lisp
;; If you already have the dependencies installed:
(asdf:load-system "breeze")
#+end_src

* Getting started with Emacs
:PROPERTIES:
:ID:       3976965c-cb83-4901-9587-3897cc207682
:END:

** Load in emacs

#+begin_src emacs-lisp
;; add breeze to emacs' load path
(add-to-list 'load-path "~/quicklisp/local-projects/breeze/emacs/")
;; load the "autoload definitions"
(require 'breeze-autoloads)
#+end_src

** Configure emacs to use =breeze-minor-mode=

Add a hook to enable breeze's minor mode in =lisp-mode= automatically:

The mode will add some bindings (most notably =C-.=, which is bound to
the command =breeze-quickfix=).

#+begin_src emacs-lisp
(add-hook 'lisp-mode-hook #'enable-breeze-minor-mode)
#+end_src

Additionally, breeze can be used as a "on-the-fly" linter for common
lisp source files by enabling flymake and configuring flymake to use
breeze.

#+begin_src emacs-lisp
;; Ensure breeze is loaded when a sly or slime connection is opened
(breeze-enable-connected-hook)

;; Enable flymake-mode in breeze-minor-mode
(breeze-minor-mode-enable-flymake-mode)

;; Configure eldoc to show both documentation and flymake's messages
;; See https://www.masteringemacs.org/article/seamlessly-merge-multiple-documentation-sources-eldoc for a fancier solution
(setf eldoc-documentation-strategy 'eldoc-documentation-compose)
#+end_src

* TODO Configure breeze                                                 :doc:
:PROPERTIES:
:ID:       a03ee62c-b289-4d28-91f4-dcc5c6e8867b
:END:

- where is it?
- what is configurable?
- how to actually configure?
- how to reload the configuations?

* See also

- [[id:279c4ea6-2004-4a7a-a2c9-905f27fae42c][Contributing]]
- [[id:bb5c6ad4-0f89-48aa-9295-13e5e248a897][Glossary]]
- [[id:31236780-159e-4a58-9019-37f57f5b4997][FAQ from newbies about common lisp]]
