:PROPERTIES:
:ID:       4836d845-7be2-4a7d-bbc5-6d7e577292c2
:END:
#+title: Documentation validation

#+begin_quote
This file contains code (mostly emacs lisp) to find any issues in
org-mode documentation files.
#+end_quote

* Some utilities

#+begin_src emacs-lisp
(defun string-set-difference (s1 s2)
  (cl-set-difference s1 s2 :test #'string=))

(defun link-to-file (file)
  (format "[[file:%s][%s]]" file file))
#+end_src

#+RESULTS:
: link-to-file

* Tags
:PROPERTIES:
:ID:       755fea16-df4d-4b87-a229-b9234b89d46b
:END:

** Tag descriptions
:PROPERTIES:
:ID:       31aae436-bbf1-4fe0-b1fb-13905ddeed22
:END:

#+NAME: tags
| Tag name     | Tag description                                                                               |
|--------------+-----------------------------------------------------------------------------------------------|
| 3rd​_parties  | Relating to a third-party, e.g. an external library.                                          |
| obsolete     | This task is now obsolete.                                                                    |
| doc          | Relating to the documentation.                                                                |
| ux           | This task is about improving the user experience                                              |
| test         | This task is about testing                                                                    |
| ops          | This task is about CI, releases, deploying docs, etc.                                         |
| easy         | This task should be easy                                                                      |
| bug          | This is an unintended bug                                                                     |
| editor       | This task relates to the integration with an editor.                                          |
| config       | Relating to breeze's configuration and setup.                                                 |
| refactor     | Relating to breeze's refactoring facilities.                                                  |
| capture      | Relating to breeze's capture feature.                                                         |
| quickproject | Relating to quickproject integration.                                                         |
| tech​_debt    | Due to an ongoing refactoring, to an old hack, incomplete implementation, missing tests, etc. |
| reader       | Relating to breeze.reader.                                                                    |
| noexport     | org-mode internal tag                                                                         |


** TODO replace the tag "reader" by "parser"

** Make sure that all tags in the table have a description.

#+begin_src emacs-lisp :var tags=tags
;; (prin1-to-string (org-get-buffer-tags))
;; (prin1-to-string tags)

;; Find tags that have no descriptions
(let ((unknown-tags
       (string-set-difference
        (mapcar #'car (org-get-buffer-tags))
        (mapcar #'car tags))))
  (or unknown-tags
      "All good, no tags without description found."))
#+end_src

#+RESULTS:
: All good, no tags without description found.

** Make sure all tasks have some tags

#+begin_src emacs-lisp
(defun breeze-tasks-find-untagged-nodes ()
  "Find all \"TODO\" nodes that don't have any tags."
  (org-roam-db-query [:select
                      [id]
                      :from nodes
                      :where (and (= todo "TODO")
                                  (not-in id [:select [node-id] :from tags]))]))

;; Visit the first untagged task, if any
(if-let ((untagged-tasks (breeze-tasks-find-untagged-nodes)))
    (cl-destructuring-bind (id) (cl-first untagged-tasks)
      (org-roam-node-visit
       (org-roam-node-from-id id)))
  (message "No untagged tasks found!"))
#+end_src

#+RESULTS:

See https://github.com/ahmed-shariff/org-roam-ql - "Query language for
org-roam".


* Make sure that all org file have a front-matter                       :doc:
:PROPERTIES:
:ID:       eb6f8b43-ee41-46f6-b23a-bcde610dc60c
:END:

For example:

#+begin_example
:PROPERTIES:
:ID:       13ea055e-4715-4583-811b-bff78ca300ee
:END:
,#+title: Candidate Features
#+end_example

#+begin_src emacs-lisp
(string-set-difference
 ;; list of org-ROAM files
 (mapcar #'file-name-base
         (org-roam-list-files))
 ;; list of org-MODE files
 (mapcar #'file-name-base
         (org-roam--shell-command-files "find . -type f -name \"*.org\" -printf \"%f\n\"")))
#+end_src

#+RESULTS:

#+begin_src shell
find . -type f -name '*.org' -exec grep '^#+title[^:]' -H '{}' ';'
#+end_src

#+RESULTS:

* Make sure that all pages are reachable from another page              :doc:
:PROPERTIES:
:ID:       c576702c-fd35-4810-b91d-4be37b306b5e
:END:

#+begin_src emacs-lisp
(defun filter-backlinks (backlinks)
  (cl-remove-if
   (lambda (backlink)
     (string-suffix-p
      "/breeze/docs/meta.org"
      (org-roam-node-file
       (org-roam-backlink-source-node backlink))))
   backlinks))

(defun node->file (node)
  (if (stringp node)
      (node->file (org-roam-node-from-id node))
    (file-name-nondirectory
     (org-roam-node-file node))))

(defun backlink->source-file (backlink)
  (node->file (org-roam-backlink-source-node backlink)))

(defun compute-backlinks-per-file ()
  (cl-loop
   with files = (make-hash-table :test 'equal)
   for node in (org-roam-node-list)
   for file = (node->file node)
   for backlinks = (filter-backlinks
                    (org-roam-backlinks-get node))
   unless (string= "meta.org" file)
   do (setf (gethash file files)
            (append
             (mapcar #'backlink->source-file backlinks)
             (gethash file files)))
   finally (return files)))

;; (mapcar #'backlink->source-file
;;         (org-roam-backlinks-get (org-roam-node-from-id "306350c9-0fb5-478b-958b-b35cae726280")))

(defun backlinks->links (backlinks)
  (cl-loop
   with links = (make-hash-table :test 'equal)
   for target being the hash-keys of backlinks
   using (hash-values backlinks)
   do (cl-loop for source in backlinks
               do (push target (gethash source links (list))))
   finally (return links)))

(defun orphan-files (backlinks)
  "list files without backlinks"
  (cl-loop
   for file being
   the hash-keys of backlinks
   using (hash-values backlinks)
   unless backlinks
   collect file))
#+end_src

** Make sure all pages are reachable from index.org
:PROPERTIES:
:ID:       ec1d7da5-9aa3-43a2-b005-36579ee915f9
:END:

#+begin_src emacs-lisp :results verbatim list replace
;; list files without backlinks
(mapcar #'link-to-file (orphan-files *backlinks*))
#+end_src

#+RESULTS:
- [[file:missing_documentation.org][missing_documentation.org]]
- [[file:feedback_from_users.org][feedback_from_users.org]]
- [[file:tasks.org][tasks.org]]
- [[file:task-generate_web_pages_from_org_files_in_docs.org][task-generate_web_pages_from_org_files_in_docs.org]]
- [[file:eclector.org][eclector.org]]
- [[file:parsing_common_lisp.org][parsing_common_lisp.org]]
- [[file:slimv.org][slimv.org]]
- [[file:file_watching.org][file_watching.org]]
- [[file:aartaka.org][aartaka.org]]
- [[file:examples_of_code_that_is_not_handled_correctly_by_slime_and_sly.org][examples_of_code_that_is_not_handled_correctly_by_slime_and_sly.org]]
- [[file:syntax_highlighting.org][syntax_highlighting.org]]
- [[file:index.org][index.org]]
- [[file:error_recovery.org][error_recovery.org]]
- [[file:rust_analyzer_blog.org][rust_analyzer_blog.org]]
- [[file:fast_incremental_peg_parsing.org][fast_incremental_peg_parsing.org]]
- [[file:listener_features.org][listener_features.org]]
- [[file:vend.org][vend.org]]
- [[file:formatting_code.org][formatting_code.org]]
- [[file:parse_files_with_conflicts.org][parse_files_with_conflicts.org]]
- [[file:linting_asd_files.org][linting_asd_files.org]]
- [[file:change_impact_analysis.org][change_impact_analysis.org]]
- [[file:case_with_correction_suggestion.org][case_with_correction_suggestion.org]]
- [[file:pagefind.org][pagefind.org]]

#+begin_src emacs-lisp
;; generate a graph (docs/pages.dot) of all th links between the
;; _files_ (not the nodes)
(with-temp-buffer
  (insert "digraph pages {")
  (let* ((ht (compute-backlinks-per-file))
         (file->id (cl-loop
                    with file->id = (make-hash-table :test 'equal)
                    for i from 0
                    for file being the hash-keys of ht
                    for id = (format "id%s" i)
                    do
                    (setf (gethash file file->id) id)
                    (insert "\n" id " [label=\"" (file-name-base file) "\"]")
                    finally (return file->id))))

    (cl-loop
     for file being the hash-keys of ht
     using (hash-values backlinks)
     ;; unless backlinks
     for name = (file-name-base file)
     for id = (gethash file file->id)
     do (dolist (backlink backlinks)
          (insert "\n" (gethash backlink file->id) " -> " id))))
  (insert "\n}")
  (write-file "pages.dot"))
#+end_src

#+begin_src emacs-lisp :results verbatim list replace
;; starting from "index.org", find the "depth" of each file

;;; TODO see also org-roam-unlinked-references-section

(defvar *backlinks* (compute-backlinks-per-file)
  "Hash table file -> list of files")

;; invariant: backlinks should contains every file expect "meta.org"
(string-set-difference
 (mapcar #'file-name-nondirectory (org-roam-list-files))
 (hash-table-keys *backlinks*))
;; => ("meta.org")

(defvar *all* (hash-table-keys *backlinks*)
  "List of all files except \"meta.org\".")

(defvar *links* (backlinks->links *backlinks*)
  "Hash table file -> list of files")

(defvar *orphans* (orphan-files *backlinks*)
  "List of files without any backlinks (no other files point to them).")

(cl-defun compute-reachability (links &optional (starting-file "index.org"))
  "Compute the set of files reachable from STARTING-FILE.
Returns a hash-table that maps each reachable files (including
STARTING-FILE) to it's distance from STARTING-FILE."
  (cl-loop
   with file->depth = (make-hash-table :test 'equal)
   for depth below 10
   for files = (list "index.org")
   then (cl-loop for file in files
                 append (cl-remove-if
                         (lambda (target) (gethash target file->depth))
                         (gethash file *links*)))
   do (dolist (file files)
        (setf (gethash file file->depth) depth))
   while files
   finally (return file->depth)))

(defvar *reachable*
  (hash-table-keys
   (compute-reachability *links*))
  "List of files reachable from \"index.org\".")

(defvar *unreachable*
  (string-set-difference *all* *reachable*)
  "List of files that are not reachable from \"index.org\".")

(defvar *cliques*
  (string-set-difference *unreachable* *orphans*)
  "List of files reachable only via links from file that are unrechable from \"index.org\".")

,*unreachable*
#+end_src

#+RESULTS:
- pagefind.org
- case_with_correction_suggestion.org
- change_impact_analysis.org
- linting_asd_files.org
- parse_files_with_conflicts.org
- formatting_code.org
- vend.org
- listener_features.org
- breeze_s_eval_v_s_sly_s_and_slime_s_eval.org
- fast_incremental_peg_parsing.org
- rust_analyzer_blog.org
- error_recovery.org
- syntax_highlighting.org
- examples_of_code_that_is_not_handled_correctly_by_slime_and_sly.org
- aartaka.org
- file_watching.org
- slimv.org
- parsing_common_lisp.org
- eclector.org
- task-generate_web_pages_from_org_files_in_docs.org
- tasks.org
- feedback_from_users.org
- missing_documentation.org



* Local variables :noexport:
# local variables:
# org-confirm-babel-evaluate: nil
# end:
