:PROPERTIES:
:ID:       4836d845-7be2-4a7d-bbc5-6d7e577292c2
:END:
#+title: Documentation validation
#+filetags: :doc:
#+property: header-args :exports both

#+begin_quote
This file contains code to find some issues in the org-mode
documentation.
#+end_quote

* Some utilities

#+begin_src emacs-lisp :results silent
(defun string-set-difference (s1 s2)
  (cl-set-difference s1 s2 :test #'string=))

(defun without-zero-width-space (string)
  (string-join
   (split-string string
                 (string (char-from-name "ZERO WIDTH SPACE"))) ""))

(defun with-zero-width-space (string)
  (string-replace
   "_"
   (concat (string (char-from-name "ZERO WIDTH SPACE")) "_")
   string))

(defun link-to-file (file)
  (if (listp file)
      (mapcar 'link-to-file file)
    (format "[[file:%s][%s]]" file (with-zero-width-space file))))
#+end_src

** Generate css file for source blocks

#+bind: org-html-htmlize-output-type css
#+begin_src emacs-lisp :var css-file="src-block.css" :results silent
(if noninteractive
    (message "Called \"non-interactively\", doing nothing...")
  (org-html-htmlize-generate-css)
  (with-current-buffer "*html*"
    (insert "/* this file was generated using `org-html-htmlize-generate-css' */\n")
    (write-file css-file)
    (kill-buffer))
  (format "#+html_head_extra: <link rel=\"stylesheet\" type=\"text/css\" href=\"%s\"/>"
          css-file))
#+end_src

* Tags
:PROPERTIES:
:ID:       755fea16-df4d-4b87-a229-b9234b89d46b
:END:

** Tag descriptions
:PROPERTIES:
:ID:       31aae436-bbf1-4fe0-b1fb-13905ddeed22
:END:

#+NAME: tags
| Tag name     | Tag description                                                                               |
|--------------+-----------------------------------------------------------------------------------------------|
| 3rd​_party   | Relating to a third-party, e.g. an external library.                                          |
| obsolete     | This task is now obsolete.                                                                    |
| doc          | Relating to the documentation.                                                                |
| ux           | This task is about improving the user experience                                              |
| test         | This task is about testing                                                                    |
| ops          | This task is about CI, releases, deploying docs, etc.                                         |
| easy         | This task should be easy                                                                      |
| bug          | This is an unintended bug                                                                     |
| editor       | This task relates to the integration with an editor.                                          |
| config       | Relating to breeze's configuration and setup.                                                 |
| refactor     | Relating to breeze's refactoring facilities.                                                  |
| capture      | Relating to breeze's capture feature.                                                         |
| quickproject | Relating to quickproject integration.                                                         |
| tech​_debt   | Due to an ongoing refactoring, to an old hack, incomplete implementation, missing tests, etc. |
| parser       | Relating to breeze.parser.                                                                    |
| reader       | Relating to cl:reader or equivalent                                                           |
| noexport     | org-mode internal tag                                                                         |
| tool         | Relating to existing tool for common lisp                                                     |
| emacs        | Relating to the emacs editor                                                                  |
| idea         | Just an idea - don't expect anything on the quality of the idea :D                            |

** TODO Move the "Tag descriptions" into its own file
:PROPERTIES:
:ID:       4a834cbb-0c75-4b6c-ada4-b82896b2b095
:END:

That should make it easier to find and use.

** TODO Make sure the table is sorted by tag name
:PROPERTIES:
:ID:       bfd598c9-0499-4313-9235-6cbc2ce79f65
:END:

** TODO Caveats: org-roam only index nodes with ids
:PROPERTIES:
:ID:       977a3d6f-3354-4ca8-9644-57395ba8d735
:END:

Most code blocks in this file uses =org-roam= to quickly gather
metadata about the =org-mode= nodes (for example, getting all the
tags). But there's one big problem with this: =org-roam= only keeps
metadata on nodes that have an ~:ID:~ property...

Reviewing the documentation can help, to make sure all appropriate
nodes have an id.

One idea to help this:
- list the org-mode files
- map over each file (~find-file~)
  - map over each node
    - if a node has a "TODO", it should have an ~:ID:~ property
      - just call ~org-id-get-create~, it's idempotent, no worry
  - at the beginning of the buffer (~(goto-char 0)~), call
    ~org-id-get-create~ to make sure the whole file has an ~:ID:~
  - make sure the file has a title
- output the list of new IDs, along with the title of the node, to
  make it easier to review

** TODO Make sure all files and nodes have a title
:PROPERTIES:
:ID:       d55ab54b-82b7-4b95-b45d-4e807357823b
:END:

** TODO Make sure all files and nodes have a unique title
:PROPERTIES:
:ID:       fdcf2b7e-2d17-4023-bd40-2fbd24624cf0
:END:

** Make sure that all tags in the documentation are present in the table
:PROPERTIES:
:ID:       225eed13-c6c4-4944-99b6-420438564f12
:END:

#+begin_src emacs-lisp :var tags=tags :results value drawer
;; Find tags that have no descriptions
(let ((unknown-tags
       (string-set-difference
        ;; List all tags used across all files
        (mapcar #'car (org-roam-db-query
                       [:select :distinct [tag] :from tags]))
        ;; minus those that are described in the table
        (mapcar (lambda (tag)
                  (cl-destructuring-bind (name description)
                      tag
                    (without-zero-width-space name)))
                tags))))
  (if (null unknown-tags)
      "All good, all tags were found in the table."
    (apply #'concat
           "The folling tags are missing from the table:\n"
           (mapcar (lambda (tag)
                     (concat " - =:" tag ":=\n"))
                   unknown-tags))))
#+end_src

#+RESULTS:
:results:
All good, all tags were found in the table.
:end:

** TODO Make sure that all tags in the table are used
:PROPERTIES:
:ID:       16c3d064-72f1-487b-89b6-57e2682f17c5
:END:

If a tag is not used anywhere in the documentation, there's no point
in keeping it here and documenting it...

** Make sure that all tags in the table have a description.
:PROPERTIES:
:ID:       c534c0d7-7172-4829-9584-3b9fb7cb4962
:END:

#+begin_src emacs-lisp :var tags=tags :results value drawer
;; Find tags that have no descriptions
(let ((tags-without-description
       (mapcar #'car
               (cl-remove-if-not
                (lambda (tag)
                  (cl-destructuring-bind (name description)
                      tag
                    (and description
                         (string-empty-p description))))
                tags))))
  (if (null tags-without-description)
      "All good, no tags without description found."
    (apply #'concat
           "The folling tags don't have any descriptions:\n"
           (mapcar (lambda (tag)
                     (concat " - =:" tag ":=\n"))
                   tags-without-description))))
#+end_src

#+RESULTS:
:results:
All good, no tags without description found.
:end:

** Make sure all tasks have some tags
:PROPERTIES:
:ID:       a838c5e3-367e-443e-8b37-594aadb2767b
:END:

That would theritically make it easier to prioritize...

#+begin_src emacs-lisp :results verbatim list replace
(defun breeze-tasks-find-untagged-nodes ()
  "Find all \"TODO\" nodes that don't have any tags."
  (org-roam-db-query [:select
                      [id title]
                      :from nodes
                      :where (and (= todo "TODO")
                                  (not-in id [:select [node-id] :from tags]))]))

;; Visit the first untagged task, if any
(defun breeze-visit-untagged-task ()
  (if-let ((untagged-tasks (breeze-tasks-find-untagged-nodes)))
      (cl-destructuring-bind (id title) (cl-first untagged-tasks)
        (org-roam-node-visit
         (org-roam-node-from-id id)))
    (message "No untagged tasks found!")))

(if-let ((untagged-tasks (breeze-tasks-find-untagged-nodes)))
    (cl-loop
     for (id title) in (breeze-tasks-find-untagged-nodes)
     collect (format "[[id:%s][%s]]\n" id title))
  '("All tasks have at least one tag."))
#+end_src

#+RESULTS:
- All tasks have at least one tag.

* Make sure that all org file have a front-matter
:PROPERTIES:
:ID:       eb6f8b43-ee41-46f6-b23a-bcde610dc60c
:END:

Example of what I mean by "front-matter":

#+begin_example
:PROPERTIES:
:ID:       13ea055e-4715-4583-811b-bff78ca300ee
:END:
,#+title: Candidate Features
#+end_example

#+begin_src emacs-lisp :results verbatim list
(let ((org-roam-files
       ;; list of org-ROAM files
       (sort
        (mapcar '(lambda (row)
                   (file-name-nondirectory (car row)))
                (org-roam-db-query [:select
                                    [file]
                                    :from nodes
                                    :where (= pos 1)
                                    ]))))
      (org-mode-files
       ;; list of org-MODE files
       (mapcar #'file-name-nondirectory
               (directory-files-recursively "." "\\.org$"))))
  (let ((missing-front-matter
         (string-set-difference org-mode-files
                                org-roam-files)))
    (link-to-file missing-front-matter)))
;; (message "All org-mode files has a corresponding org-roam node.")
#+end_src

#+RESULTS:
- [[file:sitemap.org][sitemap.org]]
- [[file:theindex.org][theindex.org]]

* Make sure that all pages are reachable from another page
:PROPERTIES:
:ID:       c576702c-fd35-4810-b91d-4be37b306b5e
:END:

#+begin_src emacs-lisp :results silent
(defun filter-backlinks (backlinks)
  (cl-remove-if
   (lambda (backlink)
     ;; TODO "sitemap.org" "theindex.org"
     (string-suffix-p
      "/breeze/docs/meta.org"
      (org-roam-node-file
       (org-roam-backlink-source-node backlink))))
   backlinks))

(defun node->file (node-designator)
  (if (stringp node-designator)
      ;; if NODE-DESIGNATOR is a string, assume it's an id
      (node->file (org-roam-node-from-id node-designator))
    (if (listp node-designator)
        ;; if NODE-DESIGNATOR is a list, assume the car is a
        ;; node-designator
        (node->file (car node-designator))
      ;; otherwise, assume that NODE-DESIGNATOR is an `org-roam-node'
      (file-name-nondirectory
       (org-roam-node-file node-designator)))))

(defun backlink->source-file (backlink)
  (node->file (org-roam-backlink-source-node backlink)))

(defun compute-backlinks-per-file ()
  (cl-loop
   with files = (make-hash-table :test 'equal)
   for node in (org-roam-node-list)
   for file = (node->file node)
   for backlinks = (filter-backlinks
                    (org-roam-backlinks-get node))
   unless (string= "meta.org" file)
   do (setf (gethash file files)
            (append
             (mapcar #'backlink->source-file backlinks)
             (gethash file files)))
   finally (return files)))

;; (mapcar #'backlink->source-file
;;         (org-roam-backlinks-get (org-roam-node-from-id "306350c9-0fb5-478b-958b-b35cae726280")))

(defun backlinks->links (backlinks)
  (cl-loop
   with links = (make-hash-table :test 'equal)
   for target being the hash-keys of backlinks
   using (hash-values backlinks)
   do (cl-loop for source in backlinks
               do (push target (gethash source links (list))))
   finally (return links)))

(defun orphan-files (backlinks)
  "list files without backlinks"
  (cl-loop
   for file being
   the hash-keys of backlinks
   using (hash-values backlinks)
   unless backlinks
   collect file))
#+end_src

** Make sure all pages are reachable from index.org
:PROPERTIES:
:ID:       ec1d7da5-9aa3-43a2-b005-36579ee915f9
:END:

#+begin_src emacs-lisp :results silent
;; starting from "index.org", find the "depth" of each file

;;; TODO see also org-roam-unlinked-references-section (View nodes
;;; that contain text that match the nodes title/alias but are not
;;; linked)

(defvar *backlinks* nil
  "Hash table file -> list of files")

(setf *backlinks* (compute-backlinks-per-file))

;; invariant: backlinks should contains every file except "meta.org"
(string-set-difference
 (mapcar #'file-name-nondirectory (org-roam-list-files))
 (hash-table-keys *backlinks*))
;; SHOULD BE:
;; => ("meta.org")
;; ACTUAL:
;; => ("sitemap.org" "meta.org" "theindex.org")

(defvar *all* nil
  "List of all files except \"meta.org\".")

(setf *all* (hash-table-keys *backlinks*))

(defvar *links* nil
  "Hash table: file -> list of files")

(setf *links* (backlinks->links *backlinks*))

(defvar *orphans* nil
  "List of files without any backlinks (no other files point to them).")

(setf *orphans* (orphan-files *backlinks*))

(cl-defun compute-reachability (links &optional (starting-file "index.org"))
  "Compute the set of files reachable from STARTING-FILE.
Returns a hash-table that maps each reachable files (including
STARTING-FILE) to it's distance from STARTING-FILE."
  (cl-loop
   with file->depth = (make-hash-table :test 'equal)
   for depth below 10
   for files = (list "index.org")
   then (cl-loop for file in files
                 append (cl-remove-if
                         (lambda (target) (gethash target file->depth))
                         (gethash file *links*)))
   do (dolist (file files)
        (setf (gethash file file->depth) depth))
   while files
   finally (return file->depth)))

(defvar *reachable* nil
  "List of files reachable from \"index.org\".")

(setf *reachable* (hash-table-keys
                   (compute-reachability *links*)))

(defvar *unreachable* nil
  "List of files that are not reachable from \"index.org\".")

(setf *unreachable* (string-set-difference *all* *reachable*))

(defvar *cliques* nil
  "List of files reachable only via links from file that are unrechable from \"index.org\".")

(setf *cliques* (string-set-difference *unreachable* *orphans*))
#+end_src

*** Unreachable files
:PROPERTIES:
:ID:       b4639fda-fc35-487d-921f-fbd948711bab
:END:

List files that are not reachable from the index

#+begin_src emacs-lisp :results verbatim list replace
(link-to-file *unreachable*)
#+end_src

#+RESULTS:

*** Orphan files - files without any links to them
:PROPERTIES:
:ID:       e9524c27-d26a-44c2-87cb-ff8918e8416d
:END:

#+begin_src emacs-lisp :results verbatim list replace
(link-to-file *orphans*)
#+end_src

#+RESULTS:

*** List of files reachable only via links to unrechable files
:PROPERTIES:
:ID:       aaed3d89-a405-4c9b-ba48-d3e4d882ae73
:END:

#+begin_src emacs-lisp :results verbatim list replace
(link-to-file *cliques*)
#+end_src

#+RESULTS:

*** TODO Graph of links between the files
:PROPERTIES:
:ID:       6a140ef1-005a-411c-bfb5-4fc61696ea4d
:END:

#+begin_src emacs-lisp
;; generate a graph (docs/pages.dot) of all the links between the
;; _files_ (not the nodes)
(with-temp-buffer
  (insert "digraph pages {")
  (let* ((ht (compute-backlinks-per-file))
         (file->id (cl-loop
                    with file->id = (make-hash-table :test 'equal)
                    for i from 0
                    for file being the hash-keys of ht
                    for id = (format "id%s" i)
                    do
                    (setf (gethash file file->id) id)
                    (insert "\n" id " [label=\"" (file-name-base file) "\"]")
                    finally (return file->id))))

    (cl-loop
     for file being the hash-keys of ht
     using (hash-values backlinks)
     ;; unless backlinks
     for name = (file-name-base file)
     for id = (gethash file file->id)
     do (dolist (backlink backlinks)
          (insert "\n" (gethash backlink file->id) " -> " id))))
  (insert "\n}")
  (write-file "pages.dot"))
#+end_src

** TODO Is it possible to fail the CI when running the check in =meta.org=
:PROPERTIES:
:ID:       a6dc287e-0458-4a81-ae27-bf5da5a2f1fb
:END:

I'm sure it is, but what would be the best way?

- Maybe just throw some error?
- Maybe accumulate the issue, print them nicely and _then_ throw an error?
- Maybe convert those "tests" into actual ert tests?

* Local variables :noexport:
# local variables:
# org-confirm-babel-evaluate: nil
# end:
